---

- name: Create a virtual machine for DBLab Engine
  ansible.builtin.import_playbook: cloud_resources.yml
  when: provision | lower != 'none'
  tags: aws, gcp, azure, digitalocean, hetzner

- name: Deploy and configure DBLab Engine software
  ansible.builtin.import_playbook: software.yml
  tags: dblab, dblab_engine

...
