---

- name: Defining host
  hosts: localhost
  gather_facts: false
  vars:
    minimal_ansible_version: 2.10.0
  tasks:
    - add_host:
        name: "{{ dle_host }}"
        groups: dle_group
      changed_when: false
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

- name: Preparing volume
  hosts: dle_group
  become: true
  become_method: sudo
  gather_facts: true
  tags: always
  any_errors_fatal: true
  vars_files:
    - vars/volume.yml
  environment: "{{ proxy_env | default({}) }}"

  roles:
    - role: volume

...
