---
- name: Provision of cloud resources (virtual machine + disk) for DLE (on {{ provision }})
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
  roles:
    - role: provision
      when: provision | lower != 'none'
...