---
# Dependencies
- name: Install python dependencies
  block:
    - name: Make sure the python3-pip package are present on controlling host
      ansible.builtin.package:
        name: python3-pip
        state: present
      register: package_status
      until: package_status is success
      delay: 10
      retries: 3
      delegate_to: 127.0.0.1
      run_once: true
      when: ansible_distribution != "MacOSX"

    - name: Install boto3 dependency on controlling host
      ansible.builtin.pip:
        name: boto3
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true

# SSH key
- block:
    # Delete the temporary ssh key from the cloud (if exists)
    - name: "AWS: Remove temporary SSH key {{ ssh_key_name }} from cloud (if any)"
      amazon.aws.ec2_key:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ ssh_key_name }}"
        region: "{{ server_location }}"
        state: absent
      when:
        - ssh_key_name is defined
        - ssh_key_name == 'dle_key_tmp'

    # if ssh_key_name and ssh_key_content is specified, add this ssh key to the cloud
    - name: "AWS: Add SSH key {{ ssh_key_name }} to cloud"
      amazon.aws.ec2_key:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ ssh_key_name }}"
        key_material: "{{ ssh_key_content }}"
        region: "{{ server_location }}"
        state: present
      register: ssh_key_result
      when:
        - ssh_key_name | length > 0
        - ssh_key_content | length > 0
  when: state == 'present'

# Create (if state is present)
- block:
    # if server_network is specified, get vpc id for this subnet
    - name: "AWS: Gather information about VPC for {{ server_network }}"
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ server_location }}"
        subnet_ids: "{{ server_network }}"
      register: vpc_subnet_info
      when: server_network | length > 0

    - name: "set_fact: vpc_id"
      set_fact:
        vpc_id: "{{ vpc_subnet_info.subnets[0].vpc_id }}"
      when:
        - server_network | length > 0
        - vpc_subnet_info.subnets[0].vpc_id is defined

    # if server_network is not specified, use default vpc subnet
    - name: "AWS: Gather information about default VPC"
      amazon.aws.ec2_vpc_net_info:
        region: "{{ server_location }}"
        filters:
          "is-default": true
      register: vpc_info
      when: server_network | length < 1

    - name: "AWS: Gather information about VPC subnet for default VPC"
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ server_location }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: vpc_subnet_info
      when:
        - server_network | length < 1
        - vpc_info.vpcs[0].id is defined

    - name: "set_fact: vpc_id"
      set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"
      when:
        - server_network | length < 1
        - vpc_info.vpcs[0].id is defined

    - name: "set_fact: server_network"
      set_fact:
        server_network: "{{ vpc_subnet_info.subnets[0].id }}"
      when:
        - server_network | length < 1
        - vpc_subnet_info.subnets[0].id is defined

    # Security Group
    - name: "AWS: Create a DLE Security Group"
      amazon.aws.ec2_security_group:
        name: dle_security_group
        state: present
        description: Enable ports to access DLE
        vpc_id: "{{ vpc_id }}"
        region: "{{ server_location }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - "{{ proxy_dle_public_port }}"
              - "{{ dle_port }}"
              - "{{ dle_ui_port }}"
              - "{{ netdata_port }}"
            cidr_ip: 0.0.0.0/0

    # Instance and volume
    - name: "AWS: Create or modify EC2 instance {{ server_name }}"
      amazon.aws.ec2_instance:
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        name: "{{ server_name | lower }}"
        state: present
        instance_type: "{{ server_type }}"
        image_id: "{{ server_image }}"
        key_name: "{{ ssh_key_name }}"
        region: "{{ server_location }}"
        security_group: dle_security_group
        vpc_subnet_id: "{{ server_network }}"
        network:
          assign_public_ip: true
          delete_on_termination: true
        volumes:
          - device_name: /dev/sdb
            ebs:
              volume_type: "{{ volume_type | default('gp3') }}"
              volume_size: "{{ volume_size }}"
              delete_on_termination: true
      register: ec2_result
      until:
        - ec2_result.instances[0].public_ip_address is defined
        - ec2_result.instances[0].public_ip_address | length > 0
      retries: 30
      delay: 10
  when: state == 'present'

# Info
- name: Show EC2 instance info
  debug:
    msg:
      - instance ID is {{ ec2_result.instances[0].instance_id }}
      - instance Image is {{ ec2_result.instances[0].image_id }}
      - instance Name is {{ ec2_result.instances[0].tags.Name }}
      - instance Type is {{ ec2_result.instances[0].instance_type }}
      - Block Storage Size is {{ volume_size }} gigabytes
      - Public IP is {{ ec2_result.instances[0].public_ip_address }}
      - Private IP is {{ ec2_result.instances[0].private_ip_address }}
  when: ec2_result.instances is defined

# set_fact: dle_host
- name: "set_fact: dle_host (for deploy DLE)"
  set_fact:
    dle_host: "ubuntu@{{ ec2_result.instances[0].public_ip_address }}"
  when: ec2_result.instances is defined

- name: "Wait for the {{ dle_host }} to be available via ssh"
  ansible.builtin.wait_for:
    host: "{{ ec2_result.instances[0].public_ip_address }}"
    port: 22
    delay: 5
    timeout: 300
  become_user: ubuntu
  when: ec2_result.instances is defined

# Delete the temporary ssh key from the cloud after creating the EC2 instance
- name: "AWS: Remove a temporary ssh key {{ ssh_key_name }} from the cloud"
  amazon.aws.ec2_key:
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
    name: "{{ ssh_key_name }}"
    region: "{{ server_location }}"
    state: absent
  register: ssh_key_result
  when:
    - ssh_key_name is defined
    - ssh_key_name == 'dle_key_tmp'

# Delete (if state is absent)
- name: "AWS: Delete a EC2 instance {{ server_name }}"
  amazon.aws.ec2_instance:
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
    name: "{{ server_name | lower }}"
    region: "{{ server_location }}"
    state: absent
  when: state == 'absent'

...