---

- name: Make sure that the required variables are specified
  fail:
    msg:
      - "One or more required variables have empty values."
      - "Please specify a value for the variables: server_name, server_type, server_image, server_location, volume_size"
  when:
    server_name | length < 1 or
    server_type | length < 1 or
    server_image | length < 1 or
    server_location | length < 1 or
    volume_size | length < 1

- name: Import tasks for AWS
  import_tasks: aws.yml
  when: provision | lower == 'aws'
  tags: aws

- name: Import tasks for GCP
  import_tasks: gcp.yml
  when: provision | lower == 'gcp'
  tags: gcp

- name: Import tasks for Azure
  import_tasks: azure.yml
  when: provision | lower == 'azure'
  tags: azure

- name: Import tasks for DigitalOcean
  import_tasks: digitalocean.yml
  when: provision | lower == 'digitalocean'
        or provision | lower == 'do'
  tags: digitalocean, do

- name: Import tasks for Hetzner Cloud
  import_tasks: hetzner.yml
  when: provision | lower == 'hetzner'
  tags: hetzner

...