---
# Debian
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  register: apt_status
  until: apt_status is success
  delay: 10
  retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when: ansible_os_family == "Debian"
  tags: install_packages

...
