---
- block:
    - name: Copy DLE plugin configuration for Netdata
      template:
        src: templates/netdata_DLE.conf.j2
        dest: "{{ dle_config_path }}/netdata_DLE.conf"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

    - name: Start Netdata container
      docker_container:
        name: netdata
        network_mode: host
        hostname: "{{ ansible_hostname }}"
        image: "postgresai/netdata-for-dle:v{{ netdata_version | replace('v', '') }}"
        capabilities: sys_ptrace
        security_opts: apparmor:unconfined
        restart_policy: unless-stopped
        container_default_behavior: "compatibility"
        volumes:
          - netdataconfig:/etc/netdata
          - "{{ dle_config_path }}/netdata_DLE.conf:/etc/netdata/charts.d/DLE.conf"
          - netdatalib:/var/lib/netdata
          - netdatacache:/var/cache/netdata
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /etc/os-release:/host/etc/os-release:ro

    - name: Check Netdata is running
      wait_for:
        port: "{{ netdata_port }}"
        host: "localhost"
        state: started
        timeout: 120
        delay: 10
      ignore_errors: false

  environment: "{{ proxy_env | default({}) }}"
  when: netdata_install is defined and netdata_install|bool
  tags: netdata

...