---
# Install Envoy Proxy
- block:  # Debian/Ubuntu
    - name: Add Envoy repository
      ansible.builtin.deb822_repository:
        name: envoyproxy-repo
        types: ["deb"]
        uris: "https://apt.envoyproxy.io"
        suites: "{{ ansible_distribution_release }}"
        components: ["main"]
        signed_by: "https://apt.envoyproxy.io/signing.key"
        enabled: true
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Envoy Proxy
      ansible.builtin.apt:
        name: "envoy"
        state: "present"
      register: apt_status
      until: apt_status is success
      delay: 10
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when:
    - ansible_os_family == "Debian"
    - proxy_install is defined
    - proxy_install | bool
  tags: proxy

# Configure Envoy Proxy
- block:
    - name: Create 'envoy' config directory
      ansible.builtin.file:
        path: /etc/envoy/
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Create 'certs' sub-directory
      ansible.builtin.file:
        path: /etc/envoy/certs
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Generate certificate
      ansible.builtin.include_role:
        name: geerlingguy.certbot
      vars:
        certbot_create_standalone_stop_services: [envoy]

    - name: Create link to directory with certificates
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: o+r
        owner: root
        group: root
        state: link
      loop:
        - { dest: /etc/envoy/certs/fullchain1.pem, src: "/etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem" }
        - { dest: /etc/envoy/certs/privkey1.pem, src: "/etc/letsencrypt/live/{{ certbot_domain }}/privkey.pem" }

    - name: Copy templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0777"
      loop:
        - { src: envoy.service.j2, dest: /etc/systemd/system/envoy.service }
        - { src: envoy.yaml.j2, dest: /etc/envoy/envoy.yaml }
        - { src: envoy.deploy.j2, dest: /etc/letsencrypt/renewal-hooks/deploy/envoy.deploy }

    - name: Enable and restart Envoy service
      ansible.builtin.service:
        name: envoy
        enabled: true
        state: restarted

    - name: Generate public URL
      ansible.builtin.set_fact:
        dblab_engine_public_url: "https://{{ certbot_domain }}:{{ proxy_dblab_engine_public_port }}/instance"

  environment: "{{ proxy_env | default({}) }}"
  when:
    - proxy_install is defined
    - proxy_install | bool
    - certbot_domain is defined
    - certbot_domain | length > 0
  tags: proxy
...
