---
# Install Envoy Proxy
- block:  # Debian/Ubuntu
    - name: Download Envoy repository apt-key
      get_url:
        url: "https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key"
        dest: /tmp/gpg.8115BA8E629CC074.key
        timeout: 60

    - name: Add Envoy repository apt-key
      apt_key:
        id: 8115BA8E629CC074
        file: /tmp/gpg.8115BA8E629CC074.key
        state: present

    - name: Add Envoy repository
      apt_repository:
        repo: "deb [arch=amd64] https://deb.dl.getenvoy.io/public/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install Envoy Proxy
      apt:
        name: "getenvoy-envoy"
        state: "present"
      register: apt_status
      until: apt_status is success
      delay: 10
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when:
    - ansible_os_family == "Debian"
    - proxy_install is defined
    - proxy_install | bool
  tags: proxy

# Configure Envoy Proxy
- block:
    - name: Create 'envoy' config directory
      file:
        path: /etc/envoy/
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Create 'certs' sub-directory
      file:
        path: /etc/envoy/certs
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Generate certificate
      include_role:
        name: geerlingguy.certbot

    - name: Create link to directory with certificates
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: o+r
        owner: root
        group: root
        state: link
      loop:
        - { dest: /etc/envoy/certs/fullchain1.pem, src: "/etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem" }
        - { dest: /etc/envoy/certs/privkey1.pem, src: "/etc/letsencrypt/live/{{ certbot_domain }}/privkey.pem" }

    - name: Copy templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0777"
      loop:
        - { src: envoy.service.j2, dest: /etc/systemd/system/envoy.service }
        - { src: envoy.yaml.j2, dest: /etc/envoy/envoy.yaml }
        - { src: envoy.deploy.j2, dest: /etc/letsencrypt/renewal-hooks/deploy/envoy.deploy }

    - name: Enable and restart Envoy service
      service:
        name: envoy
        enabled: yes
        state: restarted

    - name: Generate public URL
      set_fact:
        dle_public_url: "https://{{ certbot_domain }}:{{ proxy_dle_public_port }}/instance"

  environment: "{{ proxy_env | default({}) }}"
  when:
    - proxy_install is defined
    - proxy_install | bool
    - certbot_domain is defined
    - certbot_domain | length > 0
  tags: proxy
...
