---

- name: Remove a temporary ssh public key from the server
  authorized_key:
    user: "{{ system_user.stdout }}"
    key: "{{ hostvars['localhost']['dle_key_result']['ssh_public_key'] }}"
    state: absent
  no_log: true  # do not output public key to the ansible log
  when:
    - system_user.stdout is defined
    - hostvars['localhost']['dle_key_result']['ssh_public_key'] is defined

- block:
  - name: DLE setup finished – how to use
    run_once: true
    debug:
      msg:
        - "1) Remember your verification token (to work with UI, API, CLI): {{ dle_verification_token }}"
        - "2) SSH port forwarding for UI / API / CLI: 'ssh -N -L {{ dle_ui_port }}:127.0.0.1:{{ dle_ui_port }} {{ inventory_hostname }} -i YOUR_PRIVATE_KEY'"
        - "3) DLE UI: http://127.0.0.1:{{ dle_ui_port }}"
        - "4) DLE CLI:"
        - "  a. API URL: http://127.0.0.1:{{ dle_ui_port }}/api"
        - "  b. How to set up DLE CLI ('dblab'): https://postgres.ai/docs/how-to-guides/cli/cli-install-init"
        - "5) Monitoring:"
        - "  a. SSH port forwarding: 'ssh -N -L {{ netdata_port }}:127.0.0.1:{{ netdata_port }} {{ inventory_hostname }} -i YOUR_PRIVATE_KEY'"
        - "  b. Open: http://127.0.0.1:{{ netdata_port }}"
...
