---

- name: Remove temporary SSH public key from server
  authorized_key:
    user: "{{ system_user.stdout }}"
    key: "{{ hostvars['localhost']['dle_key_result']['ssh_public_key'] }}"
    state: absent
  no_log: true  # do not output public key to the ansible log
  when:
    - system_user.stdout is defined
    - hostvars['localhost']['dle_key_result']['ssh_public_key'] is defined

- block:  # TODO: narrow it (and find a way to get rid of double quotes)
  - name: Print usage instructions
    run_once: true
    debug:
      msg:
        - "1) Verification token (ensure to securely store it):                            "
        - "       {{ dle_verification_token }}                                             "
        - "                                                                                "
        - "2) SSH port forwarding for UI / API / CLI:                                      "
        - "       ssh -N -L {{ dle_ui_port }}:127.0.0.1:{{ dle_ui_port }} {{ inventory_hostname }} -i YOUR_PRIVATE_KEY     "
        - "                                                                                "
        - "3) DBLab UI:          http://127.0.0.1:{{ dle_ui_port }}                                     "
        - "                                                                                "
        - "4) DBLab API:                                                                   " 
        - "  - API URL:          http://127.0.0.1:{{ dle_ui_port }}/api                                 "
        - "  - API docs:         https://api.dblab.dev/                                    "
        - "                                                                                "
        - "5) DBLab CLI:                                                                   "
        - "  - CLI ('dblab') setup:                                                        "
        - "        export DBLAB_CLI_VERSION={{ dle_version }}                                          "
        - "        curl -sSL dblab.sh | bash                                               "
        - "        dblab init --environment-id={{ cli_environment_id }} --token={{ dle_verification_token }} --url=http://127.0.0.1:{{ dle_ui_port }}/api" 
        - "  - CLI docs:         https://cli-docs.dblab.dev/                               "
        - "                                                                                "
        - "6) Monitoring:                                                                  "
        - "  - SSH port forwarding:                                                        "
        - "       ssh -N -L {{ netdata_port }}:127.0.0.1:{{ netdata_port }} {{ inventory_hostname }} -i YOUR_PRIVATE_KEY    "
        - "  - Monitoring URL:   http://127.0.0.1:{{ netdata_port }}                                     "
        - "                                                                                "
        - "7) To connect to clones, use SSH port forwarding too. E.g., for clone 6000:     "
        - "       ssh -N -L 6000:127.0.0.1:6000 {{ inventory_hostname }} -i YOUR_PRIVATE_KEY      "
        - "  - and then use: 'host=localhost port=6000 user=YOUR_USER dbname=postgres'     "
  tags: info, usage
...
