---
- block:
  - name: Create configuration and logs directories
    file:
      dest: "{{ dir_item }}"
      state: directory
    loop:
      - "{{ dle_config_path }}"
      - "{{ dle_meta_path }}"
      - "{{ dle_logs_path }}"
      - "{{ dle_dump_location }}"
    loop_control:
      loop_var: dir_item

  - name: Generate conf file "{{ dle_config_path }}/server.yml"
    template:
      src: templates/server.yml.j2
      dest: "{{ dle_config_path }}/server.yml"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0644
    notify: "restart dblab_server"

  - name: Create pending.retrieval
    file:
      path: "{{ dle_meta_path }}/pending.retrieval"
      state: touch
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: u=rw,g=rw,o=rw
      modification_time: preserve
      access_time: preserve

...