---
- block:  # Debian/Ubuntu
    - name: Make sure the python3-debian package is present
      ansible.builtin.apt:
        pkg:
          - python3-debian
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3

    - name: Add repository
      ansible.builtin.deb822_repository:
        name: "{{ item.name | default(item.repo.split('//')[1].split('/')[0] | replace('.', '-')) }}"
        types: "{{ item.types | default(['deb']) }}"
        uris: "{{ item.uris | default(item.repo.split(' ')[1]) }}"
        signed_by: "{{ item.signed_by | default(item.key | default(omit)) }}"
        suites: "{{ item.suites | default(item.repo.split(' ')[2]) }}"
        components: "{{ item.components | default(item.repo.split(' ')[3]) }}"
        enabled: "{{ item.enabled | default(true) }}"
        state: present
      loop: "{{ apt_repository }}"
      when: apt_repository | length > 0

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when: ansible_os_family == "Debian"
  tags: add_repo

...
