---
- name: Get the system username
  become: false
  command: whoami
  register: system_user
  changed_when: false

- name: "Add public keys to ~{{ system_user.stdout }}/.ssh/authorized_keys"
  authorized_key:
    user: "{{ system_user.stdout }}"
    key: "{{ item }}"
    state: present
  loop: "{{ ssh_public_keys.splitlines() }}"
  no_log: true  # do not output public keys to the ansible log
  when:
    - ssh_public_keys is defined
    - ssh_public_keys | length > 0

- name: Remove a temporary ssh public key from the server
  authorized_key:
    user: "{{ system_user.stdout }}"
    key: "{{ hostvars['localhost']['dle_key_result']['ssh_public_key'] }}"
    state: absent
  no_log: true  # do not output public key to the ansible log
  when:
    - hostvars['localhost']['dle_key_result']['ssh_public_key'] is defined

...
