---
- name: Get the system username
  command: whoami
  register: system_user
  changed_when: false

- name: "Add public keys to ~{{ system_user.stdout }}/.ssh/authorized_keys"
  authorized_key:
    user: "{{ system_user.stdout }}"
    key: "{{ item }}"
    state: present
  loop: "{{ ssh_public_keys.splitlines() }}"
  no_log: true  # do not output public keys to the ansible log
  when:
    - ssh_public_keys is defined
    - ssh_public_keys | length > 0
...
