---

- block:
    - name: Install dblab CLI
      shell: |
        export DBLAB_CLI_VERSION={{ cli_version }}
        curl -sSL dblab.sh | bash
      args:
        executable: /bin/bash

    - name: Create CLI configuration directory
      file:
        dest: "{{ dle_base_path }}/cli"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644

    - name: Generate CLI conf file "{{ dle_base_path }}/cli/cli.yml"
      template:
        src: templates/cli.yml.j2
        dest: "{{ dle_base_path }}/cli/cli.yml"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0600
  when:
    - cli_install is defined
    - cli_install | bool
  tags: cli

...