---

- name: Check if the dblab CLI is initialized
  command: dblab instance status
  register: dblab_result
  changed_when: false
  failed_when: false

- block:
    - name: Download dblab CLI binary
      get_url:
        url: "https://storage.googleapis.com/database-lab-cli/{{ cli_version }}/dblab-linux-amd64"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      environment: "{{ proxy_env | default({}) }}"

    - name: Copy dblab CLI file to /usr/local/bin/
      copy:
        src: /tmp/dblab-linux-amd64
        dest: /usr/local/bin/dblab
        mode: u+x,g+x,o+x
        remote_src: true

    - name: Initialize CLI configuration
      command: >-
        dblab init
        --environment-id=dblab
        --url=http://localhost:{{ dle_port }}
        --token={{ dle_verification_token }}
        --insecure
  when:
    - cli_install is defined
    - cli_install | bool
    - dblab_result.rc != 0
  tags: cli

...